<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="DESKTOP-BJRRT0E"><DocLocation><![CDATA[F:\DemoWebShopHybrid\TestCases\AddToWIshlist]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AddToWIshlist]]></DName>
<Res><![CDATA[AddToWIshlist_23.1.2021_22.14.57]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[wishlist]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:17]]></Time>
<TimeTick>1611420677</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:17]]></Time>
<TimeTick>1611420677</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:26]]></Time>
<TimeTick>1611420686</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:26]]></Time>
<TimeTick>1611420686</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:28]]></Time>
<TimeTick>1611420688</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:28]]></Time>
<TimeTick>1611420688</TimeTick>
<NodeArgs eType="User" icon="7" nRep="18" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:28]]></Time>
<TimeTick>1611420688</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:28]]></Time>
<TimeTick>1611420688</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:29]]></Time>
<TimeTick>1611420689</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:29]]></Time>
<TimeTick>1611420689</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:29]]></Time>
<TimeTick>1611420689</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:29]]></Time>
<TimeTick>1611420689</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:29]]></Time>
<TimeTick>1611420689</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="User" icon="7" nRep="34" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="36" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:30]]></Time>
<TimeTick>1611420690</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="User" icon="7" nRep="47" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="User" icon="7" nRep="50" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:31]]></Time>
<TimeTick>1611420691</TimeTick>
<NodeArgs eType="User" icon="7" nRep="54" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:34]]></Time>
<TimeTick>1611420694</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:34]]></Time>
<TimeTick>1611420694</TimeTick>
<NodeArgs eType="User" icon="7" nRep="57" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="59" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="62" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:35]]></Time>
<TimeTick>1611420695</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="65" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="68" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Women's Running Shoe"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Value - 'Women's Running Shoe' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="User" icon="7" nRep="73" status="Passed" >
<Disp><![CDATA[Value - 'Women's Running Shoe' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Search button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="User" icon="7" nRep="76" status="Passed" >
<Disp><![CDATA[Search button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:36]]></Time>
<TimeTick>1611420696</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Women's Running Shoe ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:39]]></Time>
<TimeTick>1611420699</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="83" >
<Disp><![CDATA[[ Women's Running Shoe ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA['[ Women's Running Shoe ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:39]]></Time>
<TimeTick>1611420699</TimeTick>
<NodeArgs eType="User" icon="7" nRep="84" status="Passed" >
<Disp><![CDATA['[ Women's Running Shoe ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Add to wishlist ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:46]]></Time>
<TimeTick>1611420706</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" >
<Disp><![CDATA[[ Add to wishlist ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Whishlist is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:46]]></Time>
<TimeTick>1611420706</TimeTick>
<NodeArgs eType="User" icon="7" nRep="87" status="Passed" >
<Disp><![CDATA[Whishlist is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Add to wishlist ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:46]]></Time>
<TimeTick>1611420706</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" >
<Disp><![CDATA[[ Add to wishlist ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA['[ Add to wishlist ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:46]]></Time>
<TimeTick>1611420706</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" status="Passed" >
<Disp><![CDATA['[ Add to wishlist ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ bar-notification ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:49]]></Time>
<TimeTick>1611420709</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="93" >
<Disp><![CDATA[[ bar-notification ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[WHISHLIST ADDED ]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:49]]></Time>
<TimeTick>1611420709</TimeTick>
<NodeArgs eType="User" icon="7" nRep="94" status="Passed" >
<Disp><![CDATA[WHISHLIST ADDED ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Wishlist ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:50]]></Time>
<TimeTick>1611420710</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="97" >
<Disp><![CDATA[[ Wishlist ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Shoes added to Wishlist]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:53]]></Time>
<TimeTick>1611420713</TimeTick>
<NodeArgs eType="User" icon="7" nRep="99" status="Passed" >
<Disp><![CDATA[Shoes added to Wishlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ removefromcart ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:56]]></Time>
<TimeTick>1611420716</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" >
<Disp><![CDATA[[ removefromcart ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA['[ removefromcart ] check box' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:56]]></Time>
<TimeTick>1611420716</TimeTick>
<NodeArgs eType="User" icon="7" nRep="103" status="Passed" >
<Disp><![CDATA['[ removefromcart ] check box' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Update wishlist ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:57]]></Time>
<TimeTick>1611420717</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" >
<Disp><![CDATA[[ Update wishlist ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA['[ Update wishlist ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:21:57]]></Time>
<TimeTick>1611420717</TimeTick>
<NodeArgs eType="User" icon="7" nRep="107" status="Passed" >
<Disp><![CDATA['[ Update wishlist ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:00]]></Time>
<TimeTick>1611420720</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="110" >
<Disp><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="112" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<NodeArgs eType="User" icon="7" nRep="113" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="116" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="115" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;html tag&quot; has the expected value: &quot;INPUT&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:02]]></Time>
<TimeTick>1611420722</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="119" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="118" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="122" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="121" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="125" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="124" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Used Phone"]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="128" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj ><![CDATA[Value - 'Used Phone' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:22:03]]></Time>
<TimeTick>1611420723</TimeTick>
<NodeArgs eType="User" icon="7" nRep="129" status="Passed" >