<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="DESKTOP-BJRRT0E"><DocLocation><![CDATA[F:\DemoWebShopHybrid\TestCases\Place_Order]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Place_Order]]></DName>
<Res><![CDATA[Place_Order_23.1.2021_22.14.57]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[placeorder]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:45]]></Time>
<TimeTick>1611420465</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:45]]></Time>
<TimeTick>1611420465</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:55]]></Time>
<TimeTick>1611420475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:55]]></Time>
<TimeTick>1611420475</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:56]]></Time>
<TimeTick>1611420476</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:56]]></Time>
<TimeTick>1611420476</TimeTick>
<NodeArgs eType="User" icon="7" nRep="18" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:57]]></Time>
<TimeTick>1611420477</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@Rahman.com"]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Value - 'Rahman@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="User" icon="7" nRep="34" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="36" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:58]]></Time>
<TimeTick>1611420478</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="User" icon="7" nRep="47" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="User" icon="7" nRep="50" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:17:59]]></Time>
<TimeTick>1611420479</TimeTick>
<NodeArgs eType="User" icon="7" nRep="54" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:02]]></Time>
<TimeTick>1611420482</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Search box is avaialable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:02]]></Time>
<TimeTick>1611420482</TimeTick>
<NodeArgs eType="User" icon="7" nRep="57" status="Passed" >
<Disp><![CDATA[Search box is avaialable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:03]]></Time>
<TimeTick>1611420483</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:03]]></Time>
<TimeTick>1611420483</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="59" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:03]]></Time>
<TimeTick>1611420483</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:03]]></Time>
<TimeTick>1611420483</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="62" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ q ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:04]]></Time>
<TimeTick>1611420484</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["[ q ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:04]]></Time>
<TimeTick>1611420484</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ q ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="65" status="Passed" >
<Disp><![CDATA[[ q ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["computer"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:04]]></Time>
<TimeTick>1611420484</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Value - 'computer' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:04]]></Time>
<TimeTick>1611420484</TimeTick>
<NodeArgs eType="User" icon="7" nRep="70" status="Passed" >
<Disp><![CDATA[Value - 'computer' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:05]]></Time>
<TimeTick>1611420485</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Search Button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:05]]></Time>
<TimeTick>1611420485</TimeTick>
<NodeArgs eType="User" icon="7" nRep="73" status="Passed" >
<Disp><![CDATA[Search Button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:05]]></Time>
<TimeTick>1611420485</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:05]]></Time>
<TimeTick>1611420485</TimeTick>
<NodeArgs eType="User" icon="7" nRep="77" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Build your own cheap computer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:08]]></Time>
<TimeTick>1611420488</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="79" >
<Disp><![CDATA[[ Build your own cheap computer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Build cheap computer link is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:08]]></Time>
<TimeTick>1611420488</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" status="Passed" >
<Disp><![CDATA[Build cheap computer link is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Build your own cheap computer ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:08]]></Time>
<TimeTick>1611420488</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="83" >
<Disp><![CDATA[[ Build your own cheap computer ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA['[ Build your own cheap computer ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:08]]></Time>
<TimeTick>1611420488</TimeTick>
<NodeArgs eType="User" icon="7" nRep="84" status="Passed" >
<Disp><![CDATA['[ Build your own cheap computer ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_5_18 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:15]]></Time>
<TimeTick>1611420495</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" >
<Disp><![CDATA[[ product_attribute_72_5_18 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Processor Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:15]]></Time>
<TimeTick>1611420495</TimeTick>
<NodeArgs eType="User" icon="7" nRep="87" status="Passed" >
<Disp><![CDATA[Processor Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_5_18 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["52"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:16]]></Time>
<TimeTick>1611420496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="90" >
<Disp><![CDATA[[ product_attribute_72_5_18 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Value - '52' selected from Drop Down Field - '[ product_attribute_72_5_18 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:16]]></Time>
<TimeTick>1611420496</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" status="Passed" >
<Disp><![CDATA[Value - '52' selected from Drop Down Field - '[ product_attribute_72_5_18 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_6_19 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="93" >
<Disp><![CDATA[[ product_attribute_72_6_19 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[RAM Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="User" icon="7" nRep="94" status="Passed" >
<Disp><![CDATA[RAM Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_6_19 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["55"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="97" >
<Disp><![CDATA[[ product_attribute_72_6_19 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Value - '55' selected from Drop Down Field - '[ product_attribute_72_6_19 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="User" icon="7" nRep="98" status="Passed" >
<Disp><![CDATA[Value - '55' selected from Drop Down Field - '[ product_attribute_72_6_19 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_3_20 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="100" >
<Disp><![CDATA[[ product_attribute_72_3_20 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[RAM Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:17]]></Time>
<TimeTick>1611420497</TimeTick>
<NodeArgs eType="User" icon="7" nRep="101" status="Passed" >
<Disp><![CDATA[RAM Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_3_20 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["58"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:18]]></Time>
<TimeTick>1611420498</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="104" >
<Disp><![CDATA[[ product_attribute_72_3_20 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Value - '58' selected from Drop Down Field - '[ product_attribute_72_3_20 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:18]]></Time>
<TimeTick>1611420498</TimeTick>
<NodeArgs eType="User" icon="7" nRep="105" status="Passed" >
<Disp><![CDATA[Value - '58' selected from Drop Down Field - '[ product_attribute_72_3_20 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_8_30 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:18]]></Time>
<TimeTick>1611420498</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="107" >
<Disp><![CDATA[[ product_attribute_72_8_30 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[Office Suite CheckBox Exist]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:18]]></Time>
<TimeTick>1611420498</TimeTick>
<NodeArgs eType="User" icon="7" nRep="108" status="Passed" >
<Disp><![CDATA[Office Suite CheckBox Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_8_30 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="111" >
<Disp><![CDATA[[ product_attribute_72_8_30 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA['[ product_attribute_72_8_30 ] check box' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<NodeArgs eType="User" icon="7" nRep="112" status="Passed" >
<Disp><![CDATA['[ product_attribute_72_8_30 ] check box' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" >
<Disp><![CDATA[[ addtocart_72.EnteredQuantity ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[Quantity field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<NodeArgs eType="User" icon="7" nRep="115" status="Passed" >
<Disp><![CDATA[Quantity field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA["[ addtocart_72.EnteredQuantity ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:19]]></Time>
<TimeTick>1611420499</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="118" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ addtocart_72.EnteredQuantity ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="117" status="Passed" >
<Disp><![CDATA[[ addtocart_72.EnteredQuantity ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:20]]></Time>
<TimeTick>1611420500</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA["[ addtocart_72.EnteredQuantity ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;value&quot; has the expected value: 1.]]></Details>
<Time><![CDATA[23-01-2021 - 22:18:20]]></Time>
<TimeTick>1611420500</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="121" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ addtocart_72.EnteredQuantity ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="120" status="Passed" >
<Disp><![CDATA[[ addtocart_72.EnteredQuantity ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ]]]></Obj>