<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="PRAVIN"><DocLocation><![CDATA[E:\uft_practice_188_batch\DemoWebShopHybrid\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:11]]></Time>
<TimeTick>1619527331</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:11]]></Time>
<TimeTick>1619527331</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:19]]></Time>
<TimeTick>1619527339</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:19]]></Time>
<TimeTick>1619527339</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="User" icon="7" nRep="18" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:21]]></Time>
<TimeTick>1619527341</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="User" icon="7" nRep="34" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="36" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:22]]></Time>
<TimeTick>1619527342</TimeTick>
<NodeArgs eType="User" icon="7" nRep="47" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:23]]></Time>
<TimeTick>1619527343</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:23]]></Time>
<TimeTick>1619527343</TimeTick>
<NodeArgs eType="User" icon="7" nRep="50" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:23]]></Time>
<TimeTick>1619527343</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:23]]></Time>
<TimeTick>1619527343</TimeTick>
<NodeArgs eType="User" icon="7" nRep="54" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:25]]></Time>
<TimeTick>1619527345</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="57" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:25]]></Time>
<TimeTick>1619527345</TimeTick>
<NodeArgs eType="User" icon="7" nRep="58" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:26]]></Time>
<TimeTick>1619527346</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:26]]></Time>
<TimeTick>1619527346</TimeTick>
<NodeArgs eType="User" icon="7" nRep="62" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="67" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="70" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:27]]></Time>
<TimeTick>1619527347</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="74" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="73" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@Nandini.com"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="User" icon="7" nRep="78" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="User" icon="7" nRep="81" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="83" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="87" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="86" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="89" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@12345"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="93" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:28]]></Time>
<TimeTick>1619527348</TimeTick>
<NodeArgs eType="User" icon="7" nRep="94" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:29]]></Time>
<TimeTick>1619527349</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:29]]></Time>
<TimeTick>1619527349</TimeTick>
<NodeArgs eType="User" icon="7" nRep="97" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:29]]></Time>
<TimeTick>1619527349</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:29]]></Time>
<TimeTick>1619527349</TimeTick>
<NodeArgs eType="User" icon="7" nRep="101" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:31]]></Time>
<TimeTick>1619527351</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:31]]></Time>
<TimeTick>1619527351</TimeTick>
<NodeArgs eType="User" icon="7" nRep="105" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:33]]></Time>
<TimeTick>1619527353</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="108" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:33]]></Time>
<TimeTick>1619527353</TimeTick>
<NodeArgs eType="User" icon="7" nRep="109" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="111" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="User" icon="7" nRep="112" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="114" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="118" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="117" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="121" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="120" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@Lavish.com"]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="124" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[27-04-2021 - 18:12:34]]></Time>
<TimeTick>1619527354</TimeTick>
<NodeArgs eType="User" icon="7" nRep="125" status="Passed" >
<Disp><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">