<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-UU2F52V"><DocLocation><![CDATA[F:\CAPGEMINI DOCUMENTS\july_batch_all_docs\uft_12_sep_july_batch\SWARA_15_SEPTEMBER\DemoWebShopHybrid\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, WinForms.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:42]]></Time>
<TimeTick>1663572702</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:43]]></Time>
<TimeTick>1663572703</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:43]]></Time>
<TimeTick>1663572703</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:46]]></Time>
<TimeTick>1663572706</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:47]]></Time>
<TimeTick>1663572707</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:48]]></Time>
<TimeTick>1663572708</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:48]]></Time>
<TimeTick>1663572708</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:49]]></Time>
<TimeTick>1663572709</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:49]]></Time>
<TimeTick>1663572709</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:49]]></Time>
<TimeTick>1663572709</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:49]]></Time>
<TimeTick>1663572709</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="24" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:50]]></Time>
<TimeTick>1663572710</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:50]]></Time>
<TimeTick>1663572710</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:50]]></Time>
<TimeTick>1663572710</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<NodeArgs eType="User" icon="7" nRep="34" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="36" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:51]]></Time>
<TimeTick>1663572711</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:52]]></Time>
<TimeTick>1663572712</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:52]]></Time>
<TimeTick>1663572712</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:52]]></Time>
<TimeTick>1663572712</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:53]]></Time>
<TimeTick>1663572713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:53]]></Time>
<TimeTick>1663572713</TimeTick>
<NodeArgs eType="User" icon="7" nRep="49" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:53]]></Time>
<TimeTick>1663572713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:01:53]]></Time>
<TimeTick>1663572713</TimeTick>
<NodeArgs eType="User" icon="7" nRep="53" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;object's&nbsp;parent&nbsp;"[&nbsp;Page&nbsp;]"&nbsp;(class&nbsp;Page).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:11]]></Time>
<TimeTick>1663572731</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Title = Demo Web Shop.*<br>Mercury Class = Page<br>]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:11]]></Time>
<TimeTick>1663572731</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="75" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:11]]></Time>
<TimeTick>1663572731</TimeTick>
<NodeArgs eType="General" icon="11" nRep="77" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="19-09-2022 - 13:01:43" eTime="19-09-2022 - 13:02:11" passed="12" failed="1" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="19-09-2022 - 13:01:41" eTime="19-09-2022 - 13:02:11" passed="12" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>