<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-UU2F52V"><DocLocation><![CDATA[F:\CAPGEMINI DOCUMENTS\july_batch_all_docs\uft_12_sep_july_batch\SWARA_15_SEPTEMBER\DemoWebShopHybrid\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res9]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, WinForms.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:18]]></Time>
<TimeTick>1663572738</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:19]]></Time>
<TimeTick>1663572739</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:19]]></Time>
<TimeTick>1663572739</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:22]]></Time>
<TimeTick>1663572742</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:22]]></Time>
<TimeTick>1663572742</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:24]]></Time>
<TimeTick>1663572744</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:24]]></Time>
<TimeTick>1663572744</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:24]]></Time>
<TimeTick>1663572744</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:24]]></Time>
<TimeTick>1663572744</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:25]]></Time>
<TimeTick>1663572745</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:25]]></Time>
<TimeTick>1663572745</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="24" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:25]]></Time>
<TimeTick>1663572745</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:25]]></Time>
<TimeTick>1663572745</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:26]]></Time>
<TimeTick>1663572746</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:26]]></Time>
<TimeTick>1663572746</TimeTick>
<NodeArgs eType="User" icon="7" nRep="32" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<NodeArgs eType="User" icon="7" nRep="35" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="37" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:27]]></Time>
<TimeTick>1663572747</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="40" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:28]]></Time>
<TimeTick>1663572748</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:28]]></Time>
<TimeTick>1663572748</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="43" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:28]]></Time>
<TimeTick>1663572748</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:29]]></Time>
<TimeTick>1663572749</TimeTick>
<NodeArgs eType="User" icon="7" nRep="48" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:29]]></Time>
<TimeTick>1663572749</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:29]]></Time>
<TimeTick>1663572749</TimeTick>
<NodeArgs eType="User" icon="7" nRep="51" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:29]]></Time>
<TimeTick>1663572749</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:29]]></Time>
<TimeTick>1663572749</TimeTick>
<NodeArgs eType="User" icon="7" nRep="55" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:33]]></Time>
<TimeTick>1663572753</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:33]]></Time>
<TimeTick>1663572753</TimeTick>
<NodeArgs eType="User" icon="7" nRep="59" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:35]]></Time>
<TimeTick>1663572755</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:35]]></Time>
<TimeTick>1663572755</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="65" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<NodeArgs eType="User" icon="7" nRep="66" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="68" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:37]]></Time>
<TimeTick>1663572757</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="71" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:38]]></Time>
<TimeTick>1663572758</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:38]]></Time>
<TimeTick>1663572758</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="75" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="74" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@Nandini.com"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:39]]></Time>
<TimeTick>1663572759</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:39]]></Time>
<TimeTick>1663572759</TimeTick>
<NodeArgs eType="User" icon="7" nRep="79" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:39]]></Time>
<TimeTick>1663572759</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="81" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:39]]></Time>
<TimeTick>1663572759</TimeTick>
<NodeArgs eType="User" icon="7" nRep="82" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="84" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;password&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="87" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Password ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA["[ Password ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:40]]></Time>
<TimeTick>1663572760</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="91" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Password ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="90" status="Passed" >
<Disp><![CDATA[[ Password ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@12345"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:41]]></Time>
<TimeTick>1663572761</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:41]]></Time>
<TimeTick>1663572761</TimeTick>
<NodeArgs eType="User" icon="7" nRep="95" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:41]]></Time>
<TimeTick>1663572761</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:42]]></Time>
<TimeTick>1663572762</TimeTick>
<NodeArgs eType="User" icon="7" nRep="98" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:42]]></Time>
<TimeTick>1663572762</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="101" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:42]]></Time>
<TimeTick>1663572762</TimeTick>
<NodeArgs eType="User" icon="7" nRep="102" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:44]]></Time>
<TimeTick>1663572764</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="105" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:44]]></Time>
<TimeTick>1663572764</TimeTick>
<NodeArgs eType="User" icon="7" nRep="106" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:47]]></Time>
<TimeTick>1663572767</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="109" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:47]]></Time>
<TimeTick>1663572767</TimeTick>
<NodeArgs eType="User" icon="7" nRep="110" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:48]]></Time>
<TimeTick>1663572768</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="112" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:48]]></Time>
<TimeTick>1663572768</TimeTick>
<NodeArgs eType="User" icon="7" nRep="113" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;kind&quot; has the expected value: &quot;singleline&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="116" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="115" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;type&quot; has the expected value: &quot;text&quot;.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="119" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="118" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ Email ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebEdit]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA["[ Email ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:49]]></Time>
<TimeTick>1663572769</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="122" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Email ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="121" status="Passed" >
<Disp><![CDATA[[ Email ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@Lavish.com"]]></Details>
<Time><![CDATA[19-09-2022 - 13:02:50]]></Time>
<TimeTick>1663572770</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="125" >
<Disp><![CDATA[[ Email ].Set]]></Disp>